CREATE DataBase Exercicio_1_3

USE Exercicio_1_3

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	RG VARCHAR(9) NOT NULL UNIQUE
);

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	Nome varchar(10) NOT NULL UNIQUE
);

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL UNIQUE,
	EnderecoRua VARCHAR(20) NOT NULL
);

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	NomeVeterinario VARCHAR(15) NOT NULL
);

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet) NOT NULL,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario) NOT NULL
);

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono) NOT NULL,
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca) NOT NULL,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet) NOT NULL,
	Nome VARCHAR(10) NOT NULL,
	DataNascimentoPet DATE NOT NULL
);


DROP TABLE Veterinario