CREATE DATABASE Projeto_health_clinic
USE Projeto_health_clinic

CREATE TABLE TipoUsuario
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	Senha VARCHAR(20) NOT NULL
);

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(50) NOT NULL,
	HorarioInicioExpediente SMALLDATETIME NOT NULL,
	HorarioFimExpediente SMALLDATETIME NOT NULL,
	NomeFantasia VARCHAR(50) UNIQUE NOT NULL,
	RazaoSocial VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Paciente
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	RG CHAR(9) UNIQUE NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL
);

CREATE TABLE MedicoEspecialidade
(
	IdMedicoEspecialidade INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Medico
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	IdMedicoEspecialidade INT FOREIGN KEY REFERENCES MedicoEspecialidade(IdMedicoEspecialidade) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Consulta
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente) NOT NULL,
	Prontuario VARCHAR(250) NOT NULL
);

CREATE TABLE Comentario
(
	IdComentario INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedicO) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente) NOT NULL,
	Descricao VARCHAR(200) NOT NULL
);