CREATE DataBase Exercicio_1_3

USE Exercicio_1_3

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	RG VARCHAR(9) NOT NULL UNIQUE
);

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	Nome varchar(10) NOT NULL UNIQUE
);

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL UNIQUE,
	Endereco
);