CREATE DataBase Exercicio_1_2

USE Exercicio_1_2

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	NomeMarca VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	NomeEmpresa VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	NomeCliente VARCHAR(15) NOT NULL,
	CpfCliente VARCHAR(11) UNIQUE NOT NULL
);

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	NomeModelo VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL
);

--DROP TABLE Veiculo

ALTER TABLE Veiculo
ADD NomeVeiculo VARCHAR(15) NOT NULL

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY ,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	DataInicialAluguel DATE NOT NULL,
	DataFinalAluguel DATE NOT NULL,
	Valor FLOAT NOT NULL 
);

