CREATE DATABASE Exercicio_1_4

USE Exercicio_1_4

--DDL

CREATE TABLE Artistas
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(15) NOT NULL
);

CREATE TABLE Usuarios
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(15) NOT NULL,
	Email VARCHAR(15) NOT NULL,
	Senha VARCHAR(10) NOT NULL,
	Permissao VARCHAR(10) NOT NULL
);

CREATE TABLE Estilos
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL
);


CREATE TABLE Albuns
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista) NOT NULL,
	Titulo VARCHAR(10) NOT NULL,
	DataLancamento Date NOT NULL,
	Localizacao VARCHAR(10) NOT NULL,
	DuracaoMinutos VARCHAR(10) NOT NULL,
	Ativo VARCHAR(10) NOT NULL,
);

CREATE TABLE AlbunsEstilos
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	Nome VARCHAR
);